/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	/*
	 * move the content of a 'C' variable : val into an ARM register r0
	 */
    int val = 50;

    __asm volatile("MOV R0,%0": : "r"(val));

   /*
    * read CONTROL register to control_reg
    */
    int control_reg;

    __asm volatile("MRS %0,CONTROL":"=r"(control_reg));

    /*
     * copy the content of a 'C' variable var1 to var2
     */

    int var1 = 51, var2;

    __asm volatile("MOV %0,%1": "=r"(var2): "r"(var1));

    /*
     * copy the content of a pointer into a another variable
     */

    int p1, p2*;

    p2 = (int*) 0x20000008;

    __asm volatile("LDR %0, [%1]": "=r"(p1): "r"(p2));//p1 = *p2;

	for(;;);
}
