/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

extern void initialise_monitor_handles(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void generate_interrupt(){
	uint32_t *pISER0 = (uint32_t*)0xE000E100;
	uint32_t *pISPR  = (uint32_t*)0xE000E200;

	//enable IRQ2 interrupt
	*pISER0 |= (1 << 2);

	//generate an interrupt from software for IRQ
	*pISPR |= ( 1 << 2 );
}


int main(void)
{
	initialise_monitor_handles();

	printf("thread mode: before interrupt \n");
	generate_interrupt();
	printf("thread mode: after interrupt \n");

    /* Loop forever */
	for(;;);
}

void RTC_TAMP_IRQHandler(void)
{
	printf("in handler mode: ISR \n");
}
